input_number = int(input("Input four-digit number:"))
print("Your number is", input_number)
print (input_number // 1000)
print (input_number % 1000 // 100)
print (input_number % 100 // 10)
print (input_number % 10 // 1)